# Generated by Django 5.0.1 on 2024-01-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(null=True, upload_to='post_photos/%Y/%m/%d'),
        ),
    ]
