# Generated by Django 5.0.1 on 2024-01-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_product_alter_post_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='post_photos/%Y/%m/%d'),
        ),
    ]
